from __future__ import annotations

import os
from collections import defaultdict


_SCENARIO_COUNTS: dict[str, int] = defaultdict(int)


def _scenario_once(key: str) -> bool:
    _SCENARIO_COUNTS[key] += 1
    return _SCENARIO_COUNTS[key] == 1


def mock_qwen_response(prompt: str) -> str:
    """Deterministic Qwen-like output for local UI and workflow E2E tests.

    QWEN_MOCK_SCENARIO can intentionally bend one mock response so manual UI
    tests can exercise failed review, retry, and validation surfaces without
    depending on a real model behaving badly.
    """
    normalized = prompt.lower()
    scenario = os.environ.get("QWEN_MOCK_SCENARIO", "").strip().lower()

    if scenario == "fail_final_review_once" and ("output/final-review.md" in prompt or "you are doing the final workflow review" in normalized):
        if _scenario_once("fail_final_review_once:final_review"):
            return "Status: FAIL\n\n## Findings\n- Intentional mock failure for Playwright retry coverage.\nConfidence: 1.0\n"

    if scenario == "generate_tests_no_files" and ("you are generating automated tests" in normalized or "OUTPUT_FILE: output/test-plan.md" in prompt):
        return "Status: DONE\n\n## Test Plan\n- Intentional mock output without FILE blocks for Playwright gate failure coverage.\n"

    if scenario == "build_no_files" and ("you are implementing production code" in normalized or "OUTPUT_FILE: output/build-result.md" in prompt):
        return "Status: DONE\n\nIntentional mock build output without FILE blocks.\n"

    if "you are preparing project architecture context" in normalized or "only create or update `architecture.md`" in prompt:
        return """Status: DONE

FILE: architecture.md
CONTENT:
# Architecture

## Overview
Mock workflow project used for deterministic end-to-end verification.

## Project Structure
- Production Python modules live at the project root.
- Tests live under tests/.

## Runtime And Entry Points
- Python standard library modules are imported directly by tests.

## Data Flow
- Tests call production helper functions and assert deterministic return values.

## Testing Strategy
- Use Python unittest-compatible test files under tests/.

## Conventions
- Keep production files separate from generated tests.
- Do not write under .ai-workflow.

## Unknowns
- None blocking for mock mode.

## Update Notes
- Generated by mock Qwen for system workflow E2E coverage.
END_FILE
"""

    if "you are producing a reasoning artifact" in normalized and "output/reasoning.md" in prompt:
        return """Status: DONE

## Requirement Understanding
- The workflow should implement a small deterministic Python helper and verify it through generated tests.

## Existing Project Evidence
- Mock mode uses the selected Project Path and existing Python-compatible layout.

## Implementation Direction
- Add a root-level production module with a simple helper function.

## Files Likely To Change
- Production files: workflow_mock_feature.py
- Test files: tests/test_workflow_mock_feature.py

## Constraints
- Keep production code and tests in separate workflow steps.
- Build must not create or modify tests/ files.

## Assumptions
- Python standard library is sufficient.

## Risks
- Build output must include production FILE/CONTENT/END_FILE blocks.
"""

    if "reviewing `output/spec.md`" in normalized or "reviewing `output/todo.md`" in normalized:
        return "Status: PASS\n\n## Findings\n- None.\nConfidence: 1.0\n"

    if "you are generating automated tests" in normalized or "OUTPUT_FILE: output/test-plan.md" in prompt:
        return """Status: DONE

FILE: tests/test_workflow_mock_feature.py
CONTENT:
import unittest

from workflow_mock_feature import workflow_greeting


class WorkflowMockFeatureTests(unittest.TestCase):
    def test_workflow_greeting_is_deterministic(self):
        self.assertEqual(workflow_greeting(), "hello from controlled workflow")


if __name__ == "__main__":
    unittest.main()
END_FILE
"""

    if "you are producing a build reasoning artifact" in normalized and "output/build-reasoning.md" in prompt:
        return """Status: DONE

## Target Production Files
- workflow_mock_feature.py

## Forbidden Files
- tests/
- .ai-workflow/

## Implementation Plan
- Add a small production helper function that returns the deterministic greeting expected by tests.

## Acceptance Criteria Mapping
- AC-001 maps to workflow_greeting().
- AC-002 maps to generated tests.
- AC-003 maps to the configured test command.

## Test Awareness
- Generated tests import workflow_mock_feature.workflow_greeting and assert the greeting string.

## Retry Guidance
- None.
"""

    if "you are implementing production code" in normalized or "OUTPUT_FILE: output/build-result.md" in prompt:
        return """FILE: workflow_mock_feature.py
CONTENT:
def workflow_greeting() -> str:
    return "hello from controlled workflow"
END_FILE
"""

    if "output/final-review.md" in prompt or "you are doing the final workflow review" in normalized:
        return "Status: PASS\n\n## Summary\n- Implementation and tests satisfy the spec.\nConfidence: 1.0\n"

    if "you are generating the workflow artifact `output/spec.md`" in normalized or "OUTPUT_FILE: output/spec.md" in prompt:
        return """## Goal
- Build a small Python workflow mock feature that can be implemented and verified by the controlled workflow.

## Scope
- Add a production Python helper for the current requirement.
- Add automated tests through the Generate Tests step.
- Keep workflow artifacts deterministic for mock mode.

## Out of Scope
- Authentication, deployment, external services, and database changes.
- Any unrelated refactor outside the selected project path.

## Input
- User requirement text.
- Existing project files in the selected Project Path.
- Workflow artifacts generated by earlier steps.

## Output
- A production Python module implementing the requested mock behavior.
- Separate automated tests under tests/.
- Passing workflow review and test artifacts.

## Rules
- Production code and tests must be generated by separate workflow steps.
- Build output must create or modify only production files.
- Tests must live under tests/ and target the current requirement.
- Use a small standard-library Python implementation in mock mode.

## Acceptance Criteria
- AC-001: The production helper returns a deterministic greeting for the workflow requirement.
- AC-002: Automated tests verify the helper behavior.
- AC-003: The configured test command exits successfully.

## Unknowns
- None blocking.
"""

    if "you are generating the workflow artifact `output/todo.md`" in normalized or "OUTPUT_FILE: output/todo.md" in prompt:
        return """## Todo List
- TODO-001: Create a production helper that returns a deterministic greeting. (covers AC-001)
- TODO-002: Generate automated tests for the helper behavior. (covers AC-002)
- TODO-003: Run the configured test command and keep it green. (covers AC-003)

## Test Plan
- TEST-001: Verify the helper returns the expected deterministic greeting. (covers AC-001)
- TEST-002: Verify the tests import the production module from the project path. (covers AC-002)
- TEST-003: Verify the configured test command exits successfully. (covers AC-003)

## Done Criteria
- AC-001, AC-002, and AC-003 are implemented and verified.
"""

    return "Status: PASS\n\nReview passed in mock mode.\nConfidence: 1.0\n"
